### ISSUE TITLE
Hidden topics have no visual clue

### ISSUE THREAD

**Issue by larsaam** [bdecentgmbh/moodle-format_designer#10]
If you hide a topic on the course page. 
There are no visual clue the topic is hidden.
You have to click the drop down to see status.

**Comment by stefanscholz** [comment]
Hi!

Thanks for reporting this issue.
Unfortunately, I don't understand what you mean - can you please provide a screenshot? 

Here's how it's supposed to work:
When a section is hidden, a padlock is displayed on the course home page. This works both with the collapsed sections and the normal course type.

(Tested on 3.11 and 4.0 with Boost)

All the best
Stefan

**Comment by larsaam** [comment]
Thanks Stefan! I was wrong. I now see that there is both a text "Hidden from students" and the content is greyed out.
The padlock only show up if you have any "Access restrictions" set.

**Comment by larsaam** [comment]
Now it is easy to see if a section is hidden.

Great work!

**Comment by nettkursxyz** [comment]
@stefanscholz Unfortunately, with the latest update of Designer, the visual clue is gone again. (3.11)
