### ISSUE TITLE
Course page empty and links not functioning Moodle 4

### ISSUE THREAD

**Issue by katcher** [bdecentgmbh/moodle-format_designer#11]
Hello, I have installed the Release Candidate (Version 1.3 2022072901) for Moodle 4 on a test server.  When I enable the designer mode format, the course page displays with course title only.  The links are not functioning as well.  Is this a configuration issue?  I am unable to edit or create any activities. 

Image with Designer mode enabled:
![image](https://user-images.githubusercontent.com/4430761/190151314-ff34d3bd-849a-4e83-be9f-3b3bbf1587f6.png)

Image with Topic format:
![image](https://user-images.githubusercontent.com/4430761/190151526-b54d9da9-7c43-4e66-a34c-016645547ad8.png)

**Comment by stefanscholz** [comment]
Hi @katcher,

we are using Designer (1.3) on Moodle 4.0 for quite a while, so it's unlikely that there are any issues unless it's an incompatiblity with another plugin you've installed.

Sorry if this is a stupid question, but what happens if you enable edit mode in the top right corner?

Best
Stefan

**Comment by katcher** [comment]
Hi Stefan, nothing. The toggle moves but nothing happens.  All links etc seem to not function.  If you like, I can share a zoom link and you can have a look?

Eric

**Comment by katcher** [comment]
Fatal error: Declaration of format_designer\output\courseformat\content\cm\title::export_for_template(renderer_base $output): stdClass must be compatible with core_courseformat\output\local\content\cm\title::export_for_template(renderer_base $output): array in /public/home/course/format/designer/classes/output/courseformat/content/cm/title.php on line 47

**Comment by stefanscholz** [comment]
This is fixed in the latest release.

Many thanks for reporting! @katcher
