### ISSUE TITLE
Display activities in popups

### ISSUE THREAD

**Issue by larsaam** [bdecentgmbh/moodle-format_designer#16]
Moodle: 3.11.10
Designer: 2022081800
Theme: Boost

When "display activities in popups" is activated, next and previous buttons are not visible. 
When Pop up activities is chosen as a course format the buttons are visible.

**Comment by stefanscholz** [comment]
Thanks @larsaam for reporting this issue.

We'll look into it.

**Comment by stefanscholz** [comment]
Quick status update: we'll add the support for next/previous buttons in one of the next releases.

**Comment by stefanscholz** [comment]
Fixed in 1.5
