### ISSUE TITLE
moodle format designer triggers error 

### ISSUE THREAD

**Issue by AnnieHy** [bdecentgmbh/moodle-format_designer#18]
Hi,

I have the following issue:

I have installed the designer plugin
1) the error message "error reading from database" appears when I select and save the format under Settings.
2) I have uninstalled, reinstalled, deactivated and activated the plugin several times the error disappears after q while and everything seems to be fine, ....
3) .... but under my courses now only a blank page appears with the debugg note: This page is: General type: mycourses. Context System (context id 1). Page type my-index. Sub-page 7. 
4) after uninstalling the plugin, the error under 3) is still present
5) removing the error in the DB triggers further errors (maybe I'm doing something wrong)
6) only the import of a backup helps

Are there any plugins that interfere with the designer plugin?
I have no other course format plugins installed and no plugins that extend the standard course plugins 

I use the current moodle version 4.1.2.

Do you have an idea what happened? Thanky you!

**Comment by AnnieHy** [comment]
.

**Comment by stefanscholz** [comment]
Hi @AnnieHy,

thank you for reporting this issue, and sorry to hear that you have problems using our course format. 

I'm not aware of any incompatibilities with other plugins; there are approx. 200 active 4.1 sites using designer, and to date, we don't have any error reports.

The debug note you mention above is technically not an error — it is displayed automatically if you turn debugging on. If you turn debugging off, it disappears. (site admin > development > debugging)

I'm not sure what you mean by "removing the error in the db"?

What kind of server do you use? Which PHP version? Which database version? What operating system?
Is your server public and we could have a look?

Best
Stefan

**Comment by AnnieHy** [comment]
Hi Stefan,

thanks for your quick reply!

I forgot to mention that in the database instead of Context System (context id 1). Page type my-index. Sub-page 7 (as mentioned above) other values were stored: Context id 7 and my-index sub page 42. when I adjusted that in the database, the My Courses page  appeared again, but only for that user. I did a complete backup for the system, because even after uninstalling the plugin the My Courses page (blank page) was not back. PHP version was 8.0. 

I have now switched to PHP 8.2 and installed a completely new "clean" system without additional plugin. Everything works fine.

On my "old moodle system" the error with the empty My course page does not occur under PHP 8.2, also here everything works fine. So I think that the change to PHP 8.2 was already the solution.

I will fill my clean system with "my" additional plugins, if I notice something strange, I will give feedback.
PHP 8.2, Hosted server, Linux-System/ubuntu, Database Version | 2022.6, Mango DB

Have anice Day, best wishes

**Comment by stefanscholz** [comment]
Hi @AnnieHy ,

thanks for your response. And glad you got it working again. Without further information, my best guess would be that there was some other issue on the site or that something went wrong during installation, which caused some form of inconsistency in the database.

Marking this as closed for now, if you can reproduce the error, please let me know and we can look into it agin.

Best
Stefan
