### ISSUE TITLE
3.9: core_completionlib_testcase::test_course_delete_prerequisite failing with  moodle-format_designer Public

### ISSUE THREAD

**Issue by srdjan-catalyst** [bdecentgmbh/moodle-format_designer#20]
With the latest 3.9:

1) core_completionlib_testcase::test_course_delete_prerequisite
Invalid argument supplied for foreach()

/var/www/site/course/format/designer/backup/moodle2/backup_format_designer_plugin.class.php:61
/var/www/site/backup/moodle2/backup_plugin.class.php:74
/var/www/site/backup/util/plan/backup_structure_step.class.php:160
/var/www/site/backup/moodle2/backup_stepslib.php:341
/var/www/site/backup/util/plan/backup_structure_step.class.php:88
/var/www/site/backup/util/plan/base_task.class.php:181
/var/www/site/backup/moodle2/backup_section_task.class.php:108
/var/www/site/backup/util/plan/base_plan.class.php:191
/var/www/site/backup/util/plan/backup_plan.class.php:145
/var/www/site/backup/controller/backup_controller.class.php:419
/var/www/site/admin/tool/recyclebin/classes/category_bin.php:132
/var/www/site/admin/tool/recyclebin/lib.php:185
/var/www/site/lib/moodlelib.php:5141
/var/www/site/lib/tests/completionlib_test.php:947
/var/www/site/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/site/vendor/phpunit/phpunit/phpunit:60

To re-run:
 vendor/bin/phpunit "core_completionlib_testcase" lib/tests/completionlib_test.php

Cheers,
Srdjan

**Comment by stefanscholz** [comment]
Fixed in Release 1.5
