### ISSUE TITLE
Course index is empty, moodle 4.2.2, with all themes

### ISSUE THREAD

**Issue by ahmedhosnypro** [bdecentgmbh/moodle-format_designer#21]

**Comment by stefanscholz** [comment]
Hi @ahmedhosnypro ,

thanks for creating this issue. We're aware that Designer is not yet compatible with 4.2 (see https://moodle.org/plugins/format_designer/versions). 

We're currently working on the next release and will then also make sure it's compatible with 4.2 (and 4.3). You can expect the release within a couple of weeks.

Best
Stefan

**Comment by ahmedhosnypro** [comment]
Thanks❤️
