### ISSUE TITLE
Edit activity drop down in background

### ISSUE THREAD

**Issue by nettkursxyz** [bdecentgmbh/moodle-format_designer#4]
First of all, thanks for a great course format!

Moodle: 3.11
Browser: Chrome

When clicking edit on an activity the options are hard/impossible to click.
Example: [https://pasteboard.co/ZOm6Bk5gPPSe.png](https://pasteboard.co/ZOm6Bk5gPPSe.png)

**Comment by stefanscholz** [comment]
Which theme do you use?
And which version of designer?

**Comment by nettkursxyz** [comment]
Good point. I see now it is related to the theme. Thanks.

**Comment by stefanscholz** [comment]
Which theme are you using? Maybe we can do something about it.

We have some improvements coming up in the latest version (1.2) anyway, it's already available here in GitHub if you want to test.

**Comment by nettkursxyz** [comment]
We use the RemUI theme from Edwiser ([https://edwiser.org/remui/](https://edwiser.org/remui/))
(Since Designer works without problems in Boost I will report it to the theme provider.)

Are there any guide to check out the latest version?

I just realized you have pro versions too. Looks interesting.

**Comment by stefanscholz** [comment]
Maybe it's already fixed in 1.2, so you have a test site where you can install it?

1.2 is stable, we'll release it on Monday probably

**Comment by nettkursxyz** [comment]
Yes I have a test site.

**Comment by stefanscholz** [comment]
Sure!

**Comment by nettkursxyz** [comment]
Thank you Stefan. I just downloaded the zip and it installed fine.
The issues was also fixed with the new version!

**Comment by stefanscholz** [comment]
That's great, thanks for testing.

We'll release 1.2 shortly.

The last remaining changes are a few css tweaks, most notably for the kanban board course type.

You'll get the notification from moodle.org once we have released it.

Happy Friday! 😊
