### ISSUE TITLE
Tight left margin

### ISSUE THREAD

**Issue by larsaam** [bdecentgmbh/moodle-format_designer#9]
Thanks for a great update!

The left side margin is a little too tight?
Moodle 3.11.8 
Theme: Boost

https://paste.pics/c81a46d9b92b6b982d08700cee9833aa

**Comment by stefanscholz** [comment]
Hi!

You're right. We'll improve this in the upcoming 1.3 release. Thanks for reporting!

Best
Stefan

**Comment by larsaam** [comment]
Thanks!

**Comment by larsaam** [comment]
Now it looks nice. Thanks!
